//
//  WeiboClient.h
//  PushboxHD
//
//  Created by Xie Hasky on 11-7-23.
//  Copyright 2011年 同济大学. All rights reserved.
//

#import "OAuthHTTPRequest.h"

@class WeiboClient;

typedef void (^WCCompletionBlock)(WeiboClient *client);

@interface WeiboClient : NSObject <ASIHTTPRequestDelegate> {
    BOOL _hasError;
    NSString* _errorDesc;
    int _responseStatusCode;
    id _responseJSONObject;
    WCCompletionBlock _completionBlock;
}

@property (nonatomic, assign) BOOL hasError;
@property (nonatomic, copy) NSString* errorDesc;

// Status code generated by server side application
@property (nonatomic, assign) int responseStatusCode;

// NSDictionary or NSArray
@property (nonatomic, retain) id responseJSONObject;

// This block will be called on response with no errors
@property (nonatomic, copy) WCCompletionBlock completionBlock;

// return an autoreleased object, while gets released after one of following calls complete
+ (id)client;

// return true if user already logged in
+ (BOOL)authorized;
+ (void)signout;

- (void)authWithUsername:(NSString *)username password:(NSString *)password autosave:(BOOL)autosave;

- (void)getFollowedTimelineSinceID:(NSString *)sinceID 
					 withMaximumID:(NSString *)maxID 
                    startingAtPage:(int)page 
                             count:(int)count
                           feature:(int)feature;

- (void)getUser:(NSString *)userID;

- (void)follow:(NSString *)userID;

@end
